### ISSUE TITLE
Can i export this shell to use in another device without install gum?

### ISSUE THREAD

**Issue by clwater** [charmbracelet/gum#118]
Can i export this shell to use in another device without install gum?

**Comment by maaslalani** [comment]
Hey @clwater, I'm not quite sure what you mean exactly? Do you mind elaborating?

However, you do need `gum` installed on any device/machine that you want to use it on, so in that sense you can't use gum without installing it on the device.

**Comment by clwater** [comment]
Thanks @maaslalani 
Yeah, `gum` is so interesting for me.

I use gum to edit some shell. (My device install gum).

Can i export  my shell with gum to a normal shll ?

It means i edit this shell with gum, But i want use this shell in another device(without gum insatll).

In my environment, i need share this gum shell to other. but you know , 

When i say 'you need install gum in Binaries or brew' (Most of all, this people always no have go or brew).

They say. 'Oh, That me see later', or just 'This is good'

So, can gum provide a method to export normal shell ?

**Comment by maaslalani** [comment]
Ah, okay I see what you mean.

Currently, there is no way to export a `gum` script to a normal posix compliant shell script. If anyone uses your shell script and it is using `gum` then they also need to install `gum`. One way around this might be to prompt to install `gum` at the top of your script so that the rest of your script can use `gum`.

We might make a small code snippet that allows you to install gum with the different package managers depending on the `uname` and `arch` but we do not plan on making a way to export gum scripts to use normal posix commands.

Thank you for this issue and thanks for using `gum` ❤️

**Comment by clwater** [comment]
Thanks for your replay.

Expect to have more install method for `gum` with simple to helper more people .
