### ISSUE TITLE
Gum format --type emoji adds new line

### ISSUE THREAD

**Issue by willyw0nka** [charmbracelet/gum#146]
**Describe the bug**
When using `gum format --type emoji` new line is added to original string

**To Reproduce**
1. `gum format --type emoji :+1:  | wc -l`
4. `2` is shown as the output

Another example:
```bash
$ gum format --type emoji This is a string without emojis && echo second line
This is a string without emojis

second line
$ 
```

**Expected behavior**
`gum format --type emoji :+1:  | wc -l`  should return 1 as there is only one line in the input string

Desired output from previous example:
```bash
$ gum format --type emoji This is a string without emojis && echo second line
This is a string without emojis
second line
$ 
```
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Gum: v0.6.0

**Comment by fedeztk** [comment]
I want to add that this do not apply exclusively to the emoji format (e.g. `gum format hi` adds a new line in the same way).
The code responsible for this is at line 44:
https://github.com/charmbracelet/gum/blob/aa7683f5e03619ec3daeac8d98ff1ad1809872da/format/command.go#L30-L46

I don't know if this is a choice by the charm team but to me it seems strange.
If that is not the case and it is indeed a bug, the fix is straightforward: change the `fmt.Println` to `fmt.Print`. I don't think it deserves a whole PR since it is just two characters, but in case I can make one.

**Comment by maaslalani** [comment]
@fedeztk I think it is a bug, I don't think the new line makes sense. I would definitely accept a PR or I can make one myself 😄

**Comment by maaslalani** [comment]
Thank you @willyw0nka for this issue, definitely missed this one!
