### ISSUE TITLE
Sanitize input

### ISSUE THREAD

**Issue by muesli** [charmbracelet/gum#188]
Input containing ANSI sequences is currently not sanitized before display.

**To Reproduce**
1. Provide ANSI sequences as input to `gum filter`
2. Watch them affect rendering

**Expected behavior**
Input needs to be sanitized before displaying.

**Comment by maaslalani** [comment]
I remember thinking about this a while ago. I decided not to sanitize the input as most shell programs sanitize the input if they are being passed as a pipe output to another program.

```
bat README.md | gum filter
```

So, if ANSI sequences are part of the input perhaps they are intentional?

Curious what you think about this, happy to revisit if you think we should sanitize still though.

**Comment by muesli** [comment]
I think we should sanitize per default, otherwise it can lead to weird results (cursor repositioning in the middle of a render etc.), but maybe have an `--ansi` flag to support pre-styled content.
