### ISSUE TITLE
Allow gum file to follow symlink to directory

### ISSUE THREAD

**Issue by TheGuit** [charmbracelet/gum#191]
**Is your feature request related to a problem? Please describe.**
When navigating in my file system when I arrive to symlink to a directory it end and returns the symlink.

**Describe the solution you'd like**
Having an option (ie. --follow-symlink ) to determine if symlink must be followed when poiting to a directory.

**Comment by maaslalani** [comment]
Hey, good catch! I think if the symlink is a directory following it should be default behaviour (I don't think we need a `--follow-symlink` flag).

Thanks for making this issue!

**Comment by TheGuit** [comment]
> Hey, good catch! I think if the symlink is a directory following it should be default behaviour (I don't think we need a `--follow-symlink` flag).
> 
> Thanks for making this issue!

Yeah perhaps. Don't know exactly how to handle this. Do gum needs to return the path including the symlink or the real full path. Perhaps there is some questions to solve before coding :+1: 

- Is the default behavior is to follow symlink ?
- If follow symlink is the default behavior, do we need an option to disable follow symlink ? (for example you have system that don't have the ability to follow symlink, so be able to disable it in gum could be helpfull)
- Do we return `<symlink_path>/directory/file` or `/real/full/path/without/symlink/directory/file` ?

**Comment by brunocbreis** [comment]
Hey! I talked about this on slack as well but realized coming here would make more sense.

I personally agree that following symlinks should be default behavior, and I think the return value should be `<symlink_path>/directory/file` rather than the actual real path for consistency, because if we're choosing to traverse our files via the symlink rather than the original, I think it makes sense that we would choose that for the return value.

Maybe add a `--return-linked-path=true` option or something?


Also, if following symlinks should be the default behavior, I think having it not follow the link (i.e. return the directory) should be a result of the same option suggested in issue #193
