### ISSUE TITLE
Support --timeout and --default flag for more commands

### ISSUE THREAD

**Issue by muesli** [charmbracelet/gum#218]
Commands like choose, input, and spin should also support the `--timeout` and `--default` flags.

**Comment by deicon** [comment]
I am looking at this and wonder, if confirm works as expected 
Consider 
```
gum confirm --default=true --timeout=30s 
````
I would expect it to select YES as the default AND select Yes after 30s if the explicit timeout is triggered. 
But it actually would always return NO in case of a triggered timeout. Is this the expected behaviour ? 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/3485445/211159603-fac64252-a6c7-42df-961a-017de58cd8bd.png">
