### ISSUE TITLE
gum confirm hope to have status ctrl + c 

### ISSUE THREAD

**Issue by Simon-He95** [charmbracelet/gum#230]
gum confirm "Commit Message?"
if you press ctrl + c, you will still get 1.
I hope to have `130` to echo "have stopped", but not cancel

**Comment by deicon** [comment]
Returning 0 signals a selection, so 1 would mean no selection. In fact there are no more cases to cover. Choice needs to return 0 for a valid user choice otherwise no choice is picked by the user. No matter why. Where do you see the benefit of distinguishing the cases where no choice has been made ? Can you elaborate on the uses cases ?

**Comment by Simon-He95** [comment]
In some cases, we need to know the user's choice and do the next action, if yes, will do something, else if no, will do something, but if they want to exit, he still enters no choice.
so I want to distinguish no from exit

**Comment by deicon** [comment]
So basically a Yes, No, Cancel Dialog. Either by explicitly displaying a third cancel option or by distinguishing the return when canceled using ctrl-c. 

Sounds reasonable and seems to bother people since ages :) [Yes/No/Cancel](https://ux.stackexchange.com/questions/29393/should-yes-no-dialogs-also-have-a-cancel)

So consensus seems to be that confirm in fact has three exits. 
Confirmation
Negation
Cancel None of the above

So after understanding the issue, I would agree on beeing able to distinguish the three

**Comment by deicon** [comment]
@Simon-He95 once I finished fighting the build pipeline, I have finished a PR to enhance confirm to allow cancel option and handle CtrlC appropriately. Maybe this makes it into it

**Comment by Simon-He95** [comment]
cool

**Comment by maaslalani** [comment]
Fixed by #254, thanks for opening up this issue @Simon-He95 and for making the PR @deicon
