### ISSUE TITLE
Ability Set to set a input delimiter on `gum filter` and a output delimiter when using `--no-limit`

### ISSUE THREAD

**Issue by NatoNathan** [charmbracelet/gum#274]
As it stands you must use new lines `\n` as your delimiter in the input list for `gum filter`. Also when you use `--no-limit` the selections are concatenated without a delimiter.

It would be nice to have the ability to set a delimiter for both.

You could have something like this
```
platform=$(echo "js,android,ios" | gum filter --delimiter=",")

# and

platforms=$(echo "js|android|ios" | gum filter --delimiter="|" --no-limit --output-delimiter=",")
```

**Comment by cqroot** [comment]
I think it would be better to use bash to replace "," with "\n" in this case. for example:

```bash
echo "js,android,ios" | tr "," "\n" | gum choose
```

---

The delimiter flag is not always valid for `gum choose`.

When the input is multi-line text, `gum choose` must use "\n" to separate it instead of the delimiter you specified. Only single-line text can use the delimiter flag.

Thus, if the flag delimiter is added, the behavior of the program in the face of single-line input and multi-line input will be inconsistent.

**Comment by sheldonhull** [comment]
I ran into this today as well trying to break apart results to run for each selected item. I couldn't get my shell script to work as the no-limit behavior seems to merge them all without spaces or new lines :-(

**Comment by caarlos0** [comment]
see https://github.com/charmbracelet/gum/pull/779
