### ISSUE TITLE
`gum file` hangs if the given directory is empty

### ISSUE THREAD

**Issue by kotfu** [charmbracelet/gum#314]
**Describe the bug**
In gum 0.9.0, `gum file` hangs if the directory is empty.

**To Reproduce**
```
$ mkdir emptydir
$ gum file emptydir
Bummer. No files found.
```
From here you have to press Control-C to get your shell prompt back

**Expected behavior**
```
$ mkdir emptydir
$ gum file emptydir
no files available to select
$
```
and exit with exit code 1

**Comment by MikaelFangel** [comment]
I am not convinced that the correct solution would be exiting with exit code 1 because when you use `file` and it "hangs" you can actually use the arrow keys to navigate up in the file directory.

Demo where I press left:
![demo](https://user-images.githubusercontent.com/34864484/226315059-74d34c07-c6ab-4773-a7a1-4e37b8746412.gif)

**Comment by kotfu** [comment]
Interesting. I had no idea the left arrow worked. I think I maybe I misunderstood the intended use of `gum files`. I nowthink about it more as a generic file browser. Let me absorb this and reframe how I am using `gum files`. I now agree with you that my suggestion of expected behavior above is not correct. I think we can close this issue.
