### ISSUE TITLE
The color is missing when redirecting stderr to stdout since v0.10.0

### ISSUE THREAD

**Issue by Romain7495** [charmbracelet/gum#325]
**Describe the bug**
The color is missing when redirecting stderr to stdout

**To Reproduce**
```gum confirm "Are you sure to perform this action ?" 2>&1 | tee```
or 
```gum confirm "Are you sure to perform this action ?" |& tee```

**Expected behavior**
Having the color even if we redirect stderr to stdout

**Screenshots**
Not working since `v0.10`
![image](https://user-images.githubusercontent.com/15386726/228475851-22a420ec-6704-4670-8511-d61ec8a005fb.png)

Working without redirect
![image](https://user-images.githubusercontent.com/15386726/228476131-97e2d8af-4d5c-46ce-b6f0-adeb66255abe.png)

**Desktop**
 - ALL platform
 - wsl (ubuntu) , linux, macos

**Comment by bagl3y** [comment]
Same behavior here with 0.10.0 on WSL2 v5.15.90.1 kernel , no issues with 0.9.0

**Comment by hopefulTex** [comment]
Does this issue still occur?
Testing post- #324 seems to show no problems.

**Comment by dannyloxavier** [comment]
@hopefulTex the latest release still 0.10.0 to me.
I download the binary.
I confirm it still occur.

**Comment by hopefulTex** [comment]
It seems that since `termenv` is detecting the pipe, it's getting rid of the ansi sequences to avoid spitting out trash to `tee`.
There are ~two ways to fix this immediately,
Technically, you should be able to force a profile by setting the `CLICOLOR_FORCE` environment variable, however it did not work on my system.
If you're okay with running your own fork you can change line 31 from
`lipgloss.SetColorProfile(termenv.NewOutput(os.Stderr).Profile)`
to
`lipgloss.SetColorProfile(termenv.ANSI256)`, with `ANSI256` replaced by whatever suits your setup. [Palettes can be found here](https://github.com/muesli/termenv/blob/20f96565abe82d2c12792808f0d6bdba373e4141/profile.go) :)

If you put in a feature request for a 'force color' option, I won't be saddled by exams by mid-May if someone else doesn't get to it first :)

**Comment by vtmx** [comment]
In my case I change of colors of elements:

 ```
 export GUM_CONFIRM_UNSELECTED_BACKGROUND="0"
 export GUM_CONFIRM_UNSELECTED_FOREGROUND="15"
 export GUM_CONFIRM_SELECTED_BACKGROUND="15"
 export GUM_CONFIRM_SELECTED_FOREGROUND="0"
 ```

**Comment by elken** [comment]
Anyone finding this in the future, this seems to be resolved now; though `CLICOLOR_FORCE=true` is still needed

**Comment by caarlos0** [comment]
can't reproduce this on latest versions, nor on main.

thanks everyone!
