### ISSUE TITLE
[Feature Request] A utility to strip styling

### ISSUE THREAD

**Issue by Nickiel12** [charmbracelet/gum#33]
You might remember from my earlier issue, #19, that I am formatting `choose` options with colors. I discovered that those lines need to be cleaned of their formatting before they can be used elsewhere. This isn't a big deal because I have a workaround using `sed`.

`echo $(echo "$1" | sed 's/\x1b\[[0-9;]*[mGKHF]//g')` (thanks StackOverflow)

I just made a function with this so I could call it. But it would be nice to just:

`| gum choose --no-limit | gum remove-styling | git add`

**Comment by maaslalani** [comment]
Hey, this is a good idea, but I think it is not the approach we are going to take to solve this problem. What we will do is to detect if what we are piping to is a tty or not, if it is not we will strip all ansi sequences automatically, if it is a tty we will keep the output untouched. This should fix the root cause of your issue as the ansi output would automatically be stripped when you pipe into `git add` 🙂

**Comment by Nickiel12** [comment]
Sounds good!
