### ISSUE TITLE
gum choose doesn't work with negative options

### ISSUE THREAD

**Issue by Saad-Shaikh** [charmbracelet/gum#333]
**Describe the bug**
When gum choose is given negative options, it tries to read them as flags instead of showing them as options

**To Reproduce**
1. gum choose "0" "-1"

**Screenshots**
<img width="576" alt="Screenshot 2023-04-06 at 6 43 00 AM" src="https://user-images.githubusercontent.com/21108100/230247977-ebed7943-81ee-4be7-82b6-f97479721419.png">

**Comment by hydrargyrum** [comment]
@Saad-Shaikh try `gum choose -- 0 -1`, this trick works with many commands, not just `gum`

**Comment by hydrargyrum** [comment]
@rpodgorny It's not a shell thing :) It really is interpreted by gum, but it's a convention shared by many commands, that's why it works so often.

- if it were a shell thing, the command would not receive it at all
- you can see by not using a shell at all, for example: `python3 -c 'import os; os.execl(["gum", "choose", "--", "0", "-1"])'`
- or by running in a shell a command that doesn't follow the convention (they are rare), compare running `sqlite3` (it works) in your favourite shell with running `sqlite3 --` (it fails with `sqlite3: Error: unknown option: -`)

**Comment by rpodgorny** [comment]
> @rpodgorny It's not a shell thing :) It really is interpreted by gum, but it's a convention shared by many commands, that's why it works so often.
> 
>     * if it were a shell thing, the command would not receive it at all
> 
>     * you can see by not using a shell at all, for example: `python3 -c 'import os; os.execvp("gum", ["gum", "choose", "--", "0", "-1"])'`
> 
>     * or by running in a shell a command that doesn't follow the convention (they are rare), compare running `sqlite3` (it works) in your favourite shell with running `sqlite3 --` (it fails with `sqlite3: Error: unknown option: -`)

i was referring to the to "quoting" thing, not the "minus" thing... ;-)

**Comment by hydrargyrum** [comment]
Oops sorry I missed that, you're totally right!
