### ISSUE TITLE
Table does not work with '[' and ']' characters in output

### ISSUE THREAD

**Issue by JamesMcNee** [charmbracelet/gum#359]
**Describe the bug**
When using 'gum table' and one of the columns has `[` and `]` in it (e.g. as it's an array) then gum reports that it's invalid.

**To Reproduce**
Running the following will output an example table...
`echo "ONE   TWO\na   [\"b\", \"c\"]"`
```
ONE   TWO
a   ["b", "c"]
```

Now piping this to `gum table` e.g. `echo "ONE   TWO\na   [\"b\", \"c\"]" | gum table` yields
```
invalid data provided
```

**Expected behavior**
The table is rendered

**Desktop (please complete the following information):**
 - OS: OSX Ventura (using zsh)
 - Gum version: `0.10.0`

**Comment by tr3mor** [comment]
Hey, the problem is not really with "[" but with your input.
`gum table` expects the input to be a proper csv with a separator (comma by default, which actually breaks parsing here).
You can use any symbol via `--separator=`.
The second thing is a different way to escape double quotes in shell and csv. In shell you should use slash(as you did) but for csv you need another double quote(https://datatracker.ietf.org/doc/html/rfc4180):
```
7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

       "aaa","b""bb","ccc"
```
So, I guess what you want is
```
echo 'ONE ;  TWO      \na;"[""b"", ""c""]"' | gum table --separator=";"
# shell independent version
printf  "ONE ;  TWO      \na;\"[\"\"b\"\", \"\"c\"\"]\"" | gum table --separator=";" 
```
Which will give you
<img width="830" alt="image" src="https://github.com/charmbracelet/gum/assets/17512176/2d7748a2-a817-4b78-a3e0-b6ea7c222a60">

**Comment by JamesMcNee** [comment]
Hi @tr3mor, thanks for getting back to me!

Ah that makes total sense, given that `gum table` appeared to be working with space separated representations of tables (for example like what `kubectl` gives, which was my use case) I did not clock the fact it was expecting a `csv`! However I now realise it was just treating the entire thing as a csv with a single column when it was working 😁 

There is [an open issue](https://github.com/kubernetes/kubectl/issues/995) on `kubectl` to allow for it to output results as a CSV, but it has not had much movement in the years it's been open, so I don't hold my breath on that.

Now I understand what gum is expecting I can alter the output before piping it to gum. As the `--separator` flag only accepts a single character as the value I cannot use this to split on the triple spaces that `kubectl` uses. I may though be able to use an obscure character to get it to treat each line as a single column like it was doing usually 🤔 

Anywho, closing this off, thanks for your support.
