### ISSUE TITLE
Allow gum confirm to be interrupted in a loop. 

### ISSUE THREAD

**Issue by dzonekl** [charmbracelet/gum#469]
I am using `gum confirm` in a loop, but I am not able to interrupted it. 
I have tried using `trap` but it seems the INT signal is not received while waiting for 
confirmation. 

```
CTRL_C=false
trap 'CTRL_C=true' INT TERM
select_clean(){
    read -rA projects <<< "$(git_projects)"
    for project in $projects; do
      git="$project/.git"
      gum confirm "Remove $git" && echo "rm -rf $git"
      # Check if CTRL_C is set.
      if [[ "$CTRL_C" == "true" ]]; then
        break
      fi
    done
}
```

Is this not supported or is there a different way to interrupt the loop while using gum confirm ?

**Comment by pjg11** [comment]
Not sure if making `trap` work is possible, but I found a way.
You can break out of the loop by checking for the return value of `gum confirm`, which is 130 when pressing `CTRL+C`:

```bash
for project in $projects; do
    git="$project/.git"
    gum confirm "Remove $git" && echo "rm -rf $git"
    # Check return value, stored in $?
    if [[ "$?" -eq 130 ]]; then 
        break
    fi
done
```

**Comment by dzonekl** [comment]
Thanks @pjg11 , let me try that :-)

**Comment by ernstki** [comment]
I compared the behavior of [`dialog`](https://packages.debian.org/bookworm/dialog) and [`whiptail`](https://packages.debian.org/bookworm/whiptail) to `gum`'s and I think I prefer `gum`'s behavior.

This returns 1, identical to answering "No":

```bash
dialog --yesno "Do the thing?" 0 0 
```

And this traps the INT signal, so you can't <kbd>Ctrl</kbd>+<kbd>C</kbd> to quit at all:

```bash
whiptail --yesno "Do the thing?" 0 0
```

If the two long-standing players in the field can't agree on what to do, then maybe there's no established "best practice" for what to do in this situation. @pjg11's solution seems like the sensible thing given `gum`'s behavior, though, rather than changing how `gum` itself handles the interrupt signal.
