### ISSUE TITLE
`gum table` v0.14.4 broke height

### ISSUE THREAD

**Issue by uwe-schwarz** [charmbracelet/gum#660]
**Describe the bug**
--height=0 is taken literally and only displays the header row.

Additionally it crashes with pressing two times cursor down.

**To Reproduce**
`echo -e "col1,col2,col3\nfoo,bar,baz" | gum table`

**Expected behavior**
Display up to height lines, should default to something like before (10).

**Screenshots**
Table:
<img width="521" alt="image" src="https://github.com/user-attachments/assets/374d8f44-acb4-4873-9c80-99d10efe58e7">

Crash:
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/473cf5a7-32d5-45b6-8c6f-fd6ff191b15c">

**Desktop (please complete the following information):**
 - OS: macOS 14.6.1
 - Terminal: iTerm
 - gum version 0.14.4

**Comment by GregPK** [comment]
Reproduced on the following setup:

#### Desktop (please complete the following information):
- OS: Archlinux, kernel 6.6.47-1-lts
- Terminal: alacritty
- gum version 0.14.4

**Comment by phedayat** [comment]
I was able to reproduce the issue in the same environment as OP. Think the breaking change here is from [this commit](https://github.com/charmbracelet/gum/commit/d722a2f1b811581125911a7e1a61b4dc8e9a1ec7), and I can confirm that setting it back to 10 (or any nonzero positive int) resolves the panic during selection.

I think the problem is that when the height is set to 0, [the viewport height gets set to -1](https://github.com/charmbracelet/bubbles/blob/3eaf8da348203f12a72ce4f994334dc4cd8d91ba/table/table.go#L169), which doesn't [allow the cursor to move](https://github.com/charmbracelet/bubbles/blob/3eaf8da348203f12a72ce4f994334dc4cd8d91ba/table/table.go#L266), causing the panic.

One simple solution is to just set the height manually:
```go
if o.Height <= 0 {
    o.Height = len(data)
}
```
but I noticed that when the size of my terminal is small, the table is rendered using a seemingly different cursor start and end than I'd expect on first render, and doesn't render navigating past the top of whatever is rendered (though you *can* select items from before the first one rendered). Example using the snippet above:

<img width="716" alt="gum_test" src="https://github.com/user-attachments/assets/ba8eeb5f-507d-4eac-a8f6-5a328d54e370">

I haven't been able to track down why this happens; in the meantime, I've found that a more reasonable default which allows for smaller terminal windows (though not any size, the problem still occurs when the window has a really really small height) is to just set it as half the number of records:
```go
if o.Height <= 0 {
    o.Height = len(data) / 2
}
```

Manually setting the height via the `--height` flag to a reasonable number works as well. I've used this one-liner to run from the CLI with good results using a decently sized terminal:
```shell
HEIGHT=$(wc -l data.csv | grep -oe '[0-9]*'); gum table --height=$HEIGHT -f data.csv
```

**Comment by meowgorithm** [comment]
Oof, thanks for flagging (and for the great report). We'll get this one patched.

**Comment by meowgorithm** [comment]
So https://github.com/charmbracelet/bubbles/pull/608 should fix the panic, but it looks like the regression happened in https://github.com/charmbracelet/gum/pull/640 (in response to https://github.com/charmbracelet/gum/issues/554).

It looks like the height is essentially defaulting to `1` now, which of course isn't ideal. What would probably be best is if we defaulted the height to 12 or so, and then used the number of lines in the input if it's less than that.

**Comment by hxlnt** [comment]
A similar issue is showing up for me on `gum file` as well; only the first line is shown unless `--height` is explicitly passed in.

**Comment by meowgorithm** [comment]
@hxlnt Noted, thank you!
