### ISSUE TITLE
Filter command clears terminal when run

### ISSUE THREAD

**Issue by zachoooo** [charmbracelet/gum#93]
**Describe the bug**
Running a standard `gum filter` command causes my `tmux` terminal to refresh as if the `clear` command had been run and I lose my bash prompt. Other `gum` commands like `gum choose`don't seem to have any impact. Is this intentional behavior? Is there a setting or style option that will prevent this from happening? Could a configuration option be added so that you can select from a list without losing everything from before.

**To Reproduce**
1. Run a `gum filter` command.

**Expected behavior**
I would expect for the command to be appended to the terminal rather than for it to clear everything and reset back at the top.

**Screenshots**
Using `choose` does not remove any history:
![image](https://user-images.githubusercontent.com/1052396/182731659-54594d2c-4b67-430f-8ad7-cacbe91e6ba0.png)

Before running the `filter` command I have a prompt and text in the terminal:
![image](https://user-images.githubusercontent.com/1052396/182731815-7eaaae70-3b82-4637-a09b-b1ca64e68403.png)

After running the command, everything is replaced with the filter and the previous commands and prompt are lost:
![image](https://user-images.githubusercontent.com/1052396/182731899-4ad3a8de-203f-45b4-b45f-60fc4b4732fd.png)

**Comment by maaslalani** [comment]
Hey, there is a `--height` option that you can use but I will look into if I can fix it when there aren't too many options to choose from automatically.

**Comment by zachoooo** [comment]
It looks like the height option does work, but I need to manually set it each time and I need to update it whenever the length of the list changes. Would it be possible for the height to have an automatic option so that it takes up as much height as needed to display the list?

**Comment by maaslalani** [comment]
Yes, I am currently working on that right now. The list will take up as much space as it needs by default and if it has enough space to display inline it will otherwise if the list is too long it will enter `AltScreen` mode similar to how `fzf` does which will keep the screen intact when you return to it.

**Comment by maaslalani** [comment]
@zachoooo In the latest release, we enter `AltScreen` if there is no `--height` passed so it will clear the screen but then when the program exits everything will look as it was (no `clear` effect) which should solve most of your problems.

In the future, I will add detection to see if we can display the entire list inline and do that if the `TerminalHeight - CursorLineHeight > ListHeight` (i.e. there is enough space to display inline)

**Comment by zachoooo** [comment]
Thanks! This is nice to have. For now I've just switched to using Python and had it calculate the `height` variable based on the length of the list I'm passing in.a

**Comment by maaslalani** [comment]
Cool, this calculation should be done on `gum`'s end soon enough. Also, you could use `wc -l` (https://en.wikipedia.org/wiki/Wc_(Unix)) to count the lines if you wanted to stay in bash land.

We will have this feature implemented once the cursor position can be queried so that we can accurately predict if the terminal has enough space to display the entire list.
